adds libelf-dev
libelf-dev is required otherwise compilation fails on ubuntu 18.04 (and probably most debian based distros).

This gets hinted at in the official installer
error: Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel
This causes Make to fail on your build too.

Tried on a fresh install of 18.04 with a kernel 5.4.6 and it makes it work.